### ISSUE TITLE
Automate etcd-agent, etcd-tester log upload with fluentd

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd-test-infra#100]
https://github.com/reevoo/fluent-plugin-systemd

Or try https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=

**Comment by gyuho** [comment]
Too much time wasted, and never worked

```
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]: 2017-06-12 18:31:41 +0000 [info]: reading config file path="/fluentd/etc/fluentd.conf"
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]: /usr/lib/ruby/2.3.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /etcd-log (Errno::EACCES)
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/fileutils.rb:250:in `fu_mkdir'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin/storage_local.rb:86:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin.rb:164:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin_helper/storage.rb:111:in `block in configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin_helper/storage.rb:103:in `each'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin_helper/storage.rb:103:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluent-plugin-systemd-0.2.0/lib/fluent/plugin/in_systemd.rb:28:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin.rb:164:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/root_agent.rb:273:in `add_source'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/root_agent.rb:122:in `block in configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/root_agent.rb:118:in `each'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/root_agent.rb:118:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/engine.rb:131:in `configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/engine.rb:96:in `run_configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/supervisor.rb:755:in `run_configure'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/supervisor.rb:537:in `dry_run'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/supervisor.rb:555:in `supervise'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/supervisor.rb:461:in `run_supervisor'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /var/lib/gems/2.3.0/gems/fluentd-0.14.17/bin/fluentd:5:in `<top (required)>'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/local/bin/fluentd:22:in `load'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal docker[2037]:         from /usr/local/bin/fluentd:22:in `<main>'
Jun 12 18:31:41 tests-1-tester.c.etcd-development.internal systemd[1]: fluentd.service: Main process exited, code=exited, status=1/FAILURE
```

Forwarding to syslog should be simpler
